name : Github Actions 연습하기

on : 
  push:
    branches:
      - "**"

permissions:
  contents: read       # 저장소 내용을 읽을 수 있는 권한
  issues: write        # 이슈를 생성하고 수정할 수 있는 권한
  pull-requests: write # PR에 댓글을 달 수 있는 권한

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # 같은 워크플로우에 같은 브랜치면
  cancel-in-progress: true  # 이미 실행 중인 이전 워크플로우를 취소합니다

needs: my-job

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: "20"
 
      - name : 의존성(라이브러리) 설치
        run : npm ci

      - name : 테스트 실행하기
        run : npm run test

      - name : 빌드하기
        run : npm run build